version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
rabbitmq:
  image: rabbitmq:3-management-alpine
  container_name: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
