global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-svc:80']

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-svc:80']

  - job_name: 'sms-service'
    static_configs:
      - targets: ['sms-svc:80']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
